"""Reports Route — AI-generated PDF health summaries"""

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import text
from datetime import date, timedelta
import io

from database import get_db
from middleware.auth import get_current_user

router = APIRouter()


@router.get("/")
async def list_reports(
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    result = await db.execute(
        text("""
            SELECT id, generated_at, period_start, period_end, report_type, summary
            FROM health_reports
            WHERE user_id = :uid
            ORDER BY generated_at DESC
            LIMIT 12
        """),
        {"uid": current_user["id"]},
    )
    return {"reports": [dict(r._mapping) for r in result.fetchall()]}


@router.get("/generate")
async def generate_report(
    period: str = Query("monthly", enum=["monthly", "quarterly", "weekly"]),
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Generate a health report PDF using ReportLab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors
        from reportlab.lib.units import cm

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle("title", parent=styles["Title"],
                                     fontSize=22, textColor=colors.HexColor("#0B4F6C"))
        story.append(Paragraph("MediAid Health Report", title_style))
        story.append(Paragraph(f"Patient: {current_user.get('name', 'Patient')} | Generated: {date.today()}", styles["Normal"]))
        story.append(Spacer(1, 0.5*cm))
        story.append(Paragraph("SDG 3: Good Health and Well-Being", styles["Italic"]))
        story.append(Spacer(1, 1*cm))

        # Summary section
        story.append(Paragraph("Health Summary", styles["Heading2"]))
        story.append(Paragraph("This report covers your health metrics, medication adherence, and AI-assessed risk levels for the selected period.", styles["Normal"]))
        story.append(Spacer(1, 0.5*cm))

        # Mock vitals table
        data = [
            ["Metric", "Latest Value", "30-Day Avg", "Status"],
            ["Systolic BP", "124 mmHg", "126 mmHg", "Normal"],
            ["Diastolic BP", "82 mmHg", "83 mmHg", "Normal"],
            ["Heart Rate", "72 bpm", "74 bpm", "Normal"],
            ["Blood Glucose", "108 mg/dL", "110 mg/dL", "Monitor"],
            ["SpO₂", "98%", "98%", "Normal"],
        ]
        table = Table(data, colWidths=[5*cm, 4*cm, 4*cm, 4*cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B4F6C")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7FAFB")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
        ]))
        story.append(table)
        story.append(Spacer(1, 0.5*cm))
        story.append(Paragraph("AI Risk Assessment: MODERATE (37%)", styles["Heading3"]))
        story.append(Paragraph("Disclaimer: This report is generated by AI and is not a medical diagnosis. Always consult a qualified healthcare professional.", styles["Italic"]))

        doc.build(story)
        buffer.seek(0)

        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=mediaid-report-{date.today()}.pdf"},
        )
    except ImportError:
        return {"error": "ReportLab not installed. Run: pip install reportlab"}
